url: https://weimankow.github.io

# Site settings
title: Weiman Kow
email: weimankow@gmail.com
description: "Creative | UX Designer | Illustrator | Tech Geek"


# Team names, titles and social links
people:
- name: Weiman Kow
  pic: weiman.jpg
  position: UX Designer | Illustrator | Tech Geek
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/weiman-kow-4920499?trk=hp-identity-photo
    - title: medium
      url: https://medium.com/@weimankow
    - title: youtube
      url: https://www.youtube.com/user/lazarak33
    - title: twitter
      url: https://twitter.com/WeimanKow
  description:
    - line: Hello! I’m a UX designer interested in making the world a better place.
    - line: I love ideating great products and features based on User Stories and Business Goals.
    - line: "Tools: Sketch | Invision | Photoshop"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: linkedin
      url: # https://www.linkedin.com/in/weiman-kow-4920499?trk=hp-identity-photo
    - title: medium
      url: # https://medium.com/@weimankow
    - title: youtube
      url: https://www.youtube.com/user/lazarak33
    - title: twitter
      url: # https://twitter.com/WeimanKow

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty